### ISSUE TITLE
Use new and better graphic

### ISSUE THREAD

**Issue by soullivaneuh** [Choumiko/ModuleInserter#4]
Hi and thanks for you mod.

Could you please update it to use the new graphics for modules icons?

When I install it, they appear uglier than the original game.

Thanks.

**Comment by Choumiko** [comment]
Are you talking about the module icons in the ModuleInserter gui? I just looked closely at them, and they have a strange bend yeah. Most likely because i still use a checkbox instead of a sprite button. Will fix it when i find the time
